### ISSUE TITLE
Spectral Residualのチェックボックスをクリックして実行すると結果画像が表示されない不具合。

### ISSUE THREAD

**Issue by haruharu-1105** [mattyamonaca/AMeThyst#1]
素晴らしいアプリの公開ありがとうございます。

使わせて頂いております。
不具合報告が一点、それに伴うPRが一点あります。

- 不具合内容
Spectral Residualのチェックボックスをクリックして実行すると結果画像が表示されない。

- 再現手順
1, Colabでアプリを起動。 (メニューのランタイムよりGPUを設定済みです)
2, Spectral Residualのチェックボックスを有効化する。
3, Submitを実行時に以下のエラーが発生します。

```
!python app.py
sam_vit_h_4b8939.pth: 100% 2.39G/2.39G [00:37<00:00, 68.9MiB/s]
Running on local URL:  http://127.0.0.1:7860/
Running on public URL: https://fd27d40e75490f3de2.gradio.live/

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/dist-packages/gradio/utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
  File "/content/AMeThyst/app.py", line 67, in analysis
    results.append((spectralresidual.process(image), spectralresidual_heatmap_weight))
  File "/content/AMeThyst/tools/spectralresidual.py", line 9, in process
    saliency = cv2.saliency.StaticSaliencySpectralResidual_create()
AttributeError: module 'cv2.saliency' has no attribute 'StaticSaliencySpectralResidual_create'
```
[該当行](https://github.com/mattyamonaca/AMeThyst/blob/50039462a32d6df1d25b0be1c172fbbe189d47c1/tools/spectralresidual.py#L9)

- 原因
cv2.saliencyはopencv-contrib-pythonの方に含まれます。
[requirements.txt](https://github.com/mattyamonaca/AMeThyst/blob/50039462a32d6df1d25b0be1c172fbbe189d47c1/requirements.txt#L1)にopencv-contrib-pythonの記載が無いため。

`opencv-contrib-python==4.9.0.80
`

**Comment by mattyamonaca** [comment]
ありがとうございます！
マージしました！
